# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "articles", :force => true do |t|
    t.column "uri",   :string
    t.column "title", :string
  end

  add_index "articles", ["title"], :name => "index_articles_on_title"
  add_index "articles", ["uri"], :name => "index_articles_on_uri"

end
